# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-01-11 07:10
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    replaces = [('ccall', '0001_initial'), ('ccall', '0002_auto_20180111_1352'), ('ccall', '0003_pledge')]

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Prospect',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nric', models.CharField(max_length=15, verbose_name='NRIC')),
                ('salutation', models.CharField(max_length=10)),
                ('name', models.CharField(max_length=50)),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='Email address')),
                ('address_1', models.CharField(blank=True, max_length=50, verbose_name='Address (line 1)')),
                ('address_2', models.CharField(blank=True, max_length=50, verbose_name='Address (line 2)')),
                ('address_3', models.CharField(blank=True, max_length=50, verbose_name='Address (line 3)')),
                ('address_postal', models.CharField(blank=True, max_length=6, verbose_name='Postal code')),
                ('phone_home', models.CharField(blank=True, max_length=8, verbose_name='Home phone')),
                ('phone_mobile', models.CharField(blank=True, max_length=8, verbose_name='Mobile phone')),
                ('education_school', models.CharField(max_length=50, verbose_name='School graduated from')),
                ('education_degree', models.CharField(max_length=50, verbose_name='Degree')),
                ('education_year', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1950), django.core.validators.MaxValueValidator(2018)], verbose_name='Year of graduation')),
            ],
        ),
        migrations.CreateModel(
            name='Pledge',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pledge_amount', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Pledge amount')),
                ('pledge_fund', models.CharField(max_length=50, verbose_name='Pledge fund')),
                ('pledge_date', models.DateField(verbose_name='Pledge date')),
                ('prospect', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ccall.Prospect')),
            ],
        ),
    ]
