# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-01-08 13:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Prospect',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nric', models.CharField(max_length=15)),
                ('salutation', models.CharField(max_length=10)),
                ('name', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=254)),
                ('address_1', models.CharField(max_length=50)),
                ('address_2', models.CharField(max_length=50)),
                ('address_3', models.CharField(max_length=50)),
                ('address_postal', models.CharField(max_length=6)),
                ('phone_home', models.CharField(max_length=8)),
                ('phone_mobile', models.CharField(max_length=8)),
                ('education_school', models.CharField(max_length=50)),
                ('education_degree', models.CharField(max_length=50)),
                ('education_year', models.DateField()),
            ],
        ),
    ]
