# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-01-21 08:37
"""Add groups, apply permissions and generate some initial data."""

from __future__ import unicode_literals

from django.db import migrations


def add_permissions(apps, schema_editor):
    """Add the default permissions for all objects."""
    from django.contrib.auth.management import create_permissions

    for app_config in apps.get_app_configs():
        app_config.models_module = True
        create_permissions(app_config, verbosity=0)
        app_config.models_module = None


def add_groups(apps, schema_editor):
    """Add groups and permissions."""
    Group = apps.get_model('auth', 'Group')
    Permission = apps.get_model('auth', 'Permission')

    # create groups
    managers, _ = Group.objects.get_or_create(name='Managers')
    supervisors, _ = Group.objects.get_or_create(name='Supervisors')
    callers, _ = Group.objects.get_or_create(name='Callers')

    # apply permissions for User
    add = Permission.objects.get(codename='add_phonathonuser')
    change = Permission.objects.get(codename='change_phonathonuser')
    delete = Permission.objects.get(codename='delete_phonathonuser')
    # only managers and supervisors can change users
    managers.permissions.add(change)
    supervisors.permissions.add(change)
    # only manager can add or delete
    managers.permissions.add(add, delete)

    # apply permissions for Prospect
    add = Permission.objects.get(codename='add_prospect')
    change = Permission.objects.get(codename='change_prospect')
    delete = Permission.objects.get(codename='delete_prospect')
    # everyone can change a Prospect
    managers.permissions.add(change)
    supervisors.permissions.add(change)
    callers.permissions.add(change)
    # only manager can add or delete
    managers.permissions.add(add, delete)

    # apply permissions for Pledge
    add = Permission.objects.get(codename='add_pledge')
    change = Permission.objects.get(codename='change_pledge')
    delete = Permission.objects.get(codename='delete_pledge')
    # only managers can do this
    managers.permissions.add(add, change, delete)

    # apply permissions for Fund
    add = Permission.objects.get(codename='add_fund')
    change = Permission.objects.get(codename='change_fund')
    delete = Permission.objects.get(codename='delete_fund')
    # only managers can do this
    managers.permissions.add(add, change, delete)

    # apply permissions for Pool
    add = Permission.objects.get(codename='add_pool')
    change = Permission.objects.get(codename='change_pool')
    delete = Permission.objects.get(codename='delete_pool')
    # supervisors can change
    supervisors.permissions.add(change)
    # only managers can add or delete
    managers.permissions.add(add, change, delete)

    # apply permissions for ResultCode
    add = Permission.objects.get(codename='add_resultcode')
    change = Permission.objects.get(codename='change_resultcode')
    delete = Permission.objects.get(codename='delete_resultcode')
    # only managers can do this
    managers.permissions.add(add, change, delete)

    # apply permissions for Call
    add = Permission.objects.get(codename='add_call')
    change = Permission.objects.get(codename='change_call')
    delete = Permission.objects.get(codename='delete_call')
    # callers can add, supervisors can additionally change
    # managers can additionally delete
    callers.permissions.add(add)
    supervisors.permissions.add(add, change)
    managers.permissions.add(add, change, delete)


def create_init_superuser(apps, schema_editor):
    """Create the initial superuser."""
    from django.contrib.auth.hashers import make_password

    PhonathonUser = apps.get_model('ccall', 'PhonathonUser')
    db_alias = schema_editor.connection.alias
    PhonathonUser.objects.using(db_alias).create(username='admin', password=make_password(
        'admin'), name='Admin', email='admin@admin.com', is_staff=True, is_superuser=True)


def remove_init_superuser(apps, schema_editor):
    """Remove the initial superuser."""
    PhonathonUser = apps.get_model('ccall', 'PhonathonUser')
    db_alias = schema_editor.connection.alias
    PhonathonUser.objects.using(db_alias).get(username='admin').delete()


def create_result_codes(apps, schema_editor):
    """Create the initial result codes."""
    ResultCode = apps.get_model('ccall', 'ResultCode')
    db_alias = schema_editor.connection.alias
    ResultCode.objects.using(db_alias).bulk_create([
        ResultCode(result_code='No Answer', is_complete=False),
        ResultCode(result_code='Not Available', is_complete=False),
        ResultCode(result_code='Interested (EM)'),
        ResultCode(result_code='Interested (DM)'),
        ResultCode(result_code='Specified Pledge (EM)'),
        ResultCode(result_code='Specified Pledge (DM)'),
        ResultCode(result_code='Already Pledged'),
        ResultCode(result_code='No Pledge'),
        ResultCode(result_code='Other Contact'),
        ResultCode(result_code='Wrong Number'),
        ResultCode(result_code='Out of Country'),
        ResultCode(result_code='Deceased'),
        ResultCode(result_code='DNC'),
    ])


def remove_result_codes(apps, schema_editor):
    """Remove the initial result codes."""
    ResultCode = apps.get_model('ccall', 'ResultCode')
    db_alias = schema_editor.connection.alias
    ResultCode.objects.using(db_alias).all().delete()


class Migration(migrations.Migration):

    dependencies = [
        ('ccall', '0001_initial'),
        ('auth', '__latest__')
    ]

    operations = [
        migrations.RunPython(add_permissions, migrations.RunPython.noop),
        migrations.RunPython(add_groups, migrations.RunPython.noop),
        migrations.RunPython(create_init_superuser, remove_init_superuser),
        migrations.RunPython(create_result_codes, remove_result_codes)
    ]
