# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-01-15 10:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ccall', '0001_squashed_0003_pledge'),
    ]

    operations = [
        migrations.AlterField(
            model_name='prospect',
            name='nric',
            field=models.CharField(max_length=15, unique=True, verbose_name='NRIC'),
        ),
    ]
