# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-01-11 05:52
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ccall', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='prospect',
            name='address_1',
            field=models.CharField(blank=True, max_length=50, verbose_name='Address (line 1)'),
        ),
        migrations.AlterField(
            model_name='prospect',
            name='address_2',
            field=models.CharField(blank=True, max_length=50, verbose_name='Address (line 2)'),
        ),
        migrations.AlterField(
            model_name='prospect',
            name='address_3',
            field=models.CharField(blank=True, max_length=50, verbose_name='Address (line 3)'),
        ),
        migrations.AlterField(
            model_name='prospect',
            name='address_postal',
            field=models.CharField(blank=True, max_length=6, verbose_name='Postal code'),
        ),
        migrations.AlterField(
            model_name='prospect',
            name='education_degree',
            field=models.CharField(max_length=50, verbose_name='Degree'),
        ),
        migrations.AlterField(
            model_name='prospect',
            name='education_school',
            field=models.CharField(max_length=50, verbose_name='School graduated from'),
        ),
        migrations.AlterField(
            model_name='prospect',
            name='education_year',
            field=models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1950), django.core.validators.MaxValueValidator(2018)], verbose_name='Year of graduation'),
        ),
        migrations.AlterField(
            model_name='prospect',
            name='email',
            field=models.EmailField(blank=True, max_length=254, verbose_name='Email address'),
        ),
        migrations.AlterField(
            model_name='prospect',
            name='nric',
            field=models.CharField(max_length=15, verbose_name='NRIC'),
        ),
        migrations.AlterField(
            model_name='prospect',
            name='phone_home',
            field=models.CharField(blank=True, max_length=8, verbose_name='Home phone'),
        ),
        migrations.AlterField(
            model_name='prospect',
            name='phone_mobile',
            field=models.CharField(blank=True, max_length=8, verbose_name='Mobile phone'),
        ),
    ]
