# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-03-18 16:03
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ccall', '0002_add_data'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='pool',
            unique_together=set([('name', 'project')]),
        ),
    ]
