# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-03-26 06:29
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ccall', '0003_auto_20180319_0003'),
    ]

    operations = [
        migrations.AddField(
            model_name='call',
            name='project',
            field=models.ForeignKey(
                default=1, on_delete=django.db.models.deletion.CASCADE, to='ccall.Project', verbose_name='Project'),
            preserve_default=False,
        ),
    ]
