# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-03-26 13:21
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ccall', '0005_auto_20180326_1545'),
    ]

    operations = [
        migrations.RenameField(
            model_name='assignment',
            old_name='user',
            new_name='caller',
        ),
    ]
